### PR TITLE
Bin2llvmir improvements

### PR DESCRIPTION
**Pull request by Alexander-Alekseev**
Several fixes for the bin2llvmir project.

### CODE REVIEW

**Comment by Alexander-Alekseev** [comment]
Offtopic: please let me know if number of commits in a row isn't a good way. I will 'squash' them.

**Comment by s3rvac** [comment]
> Offtopic: please let me know if several commits in a row isn't a good way. I will 'squash' them.

This is totally fine. It is better to create atomic commits with good commit messages than huge commits with unrelated changes and generic commit messages that tell you nothing about the reason why the change was necessary.

**Comment by PeterMatula** [comment]
Thanks, i will look into it, but not right away.

**Comment by PeterMatula** [comment]
Looks good.

There were some good catches in there. May I ask how did you find them? Did you just go over the code yourself, or compiler warnings, or used some code analysis tool?

**Comment by Alexander-Alekseev** [comment]
For changes in these commits I used PVS-Studio (https://www.viva64.com/en/pvs-studio/).

**Pull request merged**
