### PR TITLE
Update README.md to include `libfl-dev` dependency.

### PR DESCRIPTION
**Pull request by droope**
Hi there,

Simple PR for the addition of a required dependency.

Thanks,
Pedro

### CODE REVIEW

**Comment by PeterMatula** [comment]
What distribution are you using? You are right that we need `libfl-dev` package, but on both Ubuntu and Debian we tested on, this package is a dependency of `flex` that is in our package list:

Ubuntu:
```
# apt install flex
...
The following NEW packages will be installed:
  binutils binutils-common binutils-x86-64-linux-gnu cpp cpp-7 flex gcc gcc-7
  gcc-7-base libasan4 libatomic1 libbinutils libc-dev-bin libc6-dev libcc1-0
  libcilkrts5 libfl-dev libfl2 libgcc-7-dev libgomp1 libisl19 libitm1 liblsan0
  libmpc3 libmpfr6 libmpx2 libquadmath0 libsigsegv2 libtsan0 libubsan0
  linux-libc-dev m4 manpages manpages-dev
```

Debian:
```
# apt install flex
...
The following NEW packages will be installed:
  binutils cpp cpp-6 flex gcc gcc-6 libasan3 libatomic1 libc-dev-bin libc6-dev
  libcc1-0 libcilkrts5 libfl-dev libgcc-6-dev libgmp10 libgomp1 libisl15
  libitm1 liblsan0 libmpc3 libmpfr4 libmpx2 libquadmath0 libsigsegv2 libtsan0
  libubsan0 linux-libc-dev m4 manpages manpages-dev
```

**Comment by droope** [comment]
Hi,

I can confirm in my case it didn't install automatically for whatever reason, here is the output of `apt-cache depends flex`:

```
apt-cache depends flex
flex
 |PreDepends: debconf
  PreDepends: <debconf-2.0>
    cdebconf
    debconf
  Depends: libc6
  Depends: m4
 |Recommends: gcc
  Recommends: <c-compiler>
    bcc
    clang-3.9
    clang-4.0
    clang-5.0
    clang-6.0
    gcc
    gcc-6
    gcc-7
    gcc-8
    tcc
  Recommends: libfl-dev
  Suggests: bison
  Suggests: build-essential
  Suggests: flex-doc
```

Here's my debian version info:

```
# cat /etc/debian_version 
buster/sid
# uname -a
Linux cfhghgc-pc 4.16.0-2-amd64 #1 SMP Debian 4.16.16-2 (2018-06-22) x86_64 GNU/Linux
```

I'm not certain why it didn't install, it may be related to a new default setting or a setting I overrode some time ago, or it could be a user error as well. The main problem was that the error did not trigger until after compilation reached 100% so diagnosing the issue was expensive, time-wise. 

I'd like to take this opportunity to thank you all for your work and for retdec, I think it's a great piece of software engineering tackling a really challenging problem.

**Comment by PeterMatula** [comment]
Ok, fair enough. We need the library, it is not guaranteed that it gets installed automatically, so it should be in the list.

**Comment by droope** [comment]
Sweet! perfect

**Pull request merged**
