### PR TITLE
[WIP] Add Travis CI

### PR DESCRIPTION
**Pull request by lilianmoraru**
The idea in the end is to create Linux binaries with the help of Travis(To reduce expectations: I don't yet plan to do this task), but not yet available here.

### CODE REVIEW

**Comment by lilianmoraru** [comment]
You can follow the status of the build here: https://travis-ci.org/lilianmoraru/retdec/builds/318839555

**Comment by lilianmoraru** [comment]
Travis overwrites CC and CXX, need to handle that...

**Comment by lilianmoraru** [comment]
Seems like `capstone2llvmir` won't be compiling on clang...: https://travis-ci.org/lilianmoraru/retdec/jobs/318848946#L1045

**Comment by lilianmoraru** [comment]
Timed out - takes to much time to compile all the dependencies.
I will make it compile only `capstone2llvmir` - let it cache it and then you can switch back to building everything.

**Comment by s3rvac** [comment]
Thank you for the effort. A couple of notes from me:
* I am afraid we would not be able to use the free version of Travis CI due to their time limits. Nevertheless, its worth a shot as I might be wrong.
* As for the unsuccessful Clang build, it failed with the following error:
    ```
    tl-cpputils/range.h:179:39: error: no template named 'enable_if_t' in namespace 'std'; did you mean 'enable_if'?
    ```
    RetDec build requires a C++14-capable compiler and standard library implementation. [`std::enable_if_t`](http://en.cppreference.com/w/cpp/types/enable_if) was introduced into the standard library in C++14, but it seems that the version of the standard library that was used during the build did not yet have that implementation.

**Comment by lilianmoraru** [comment]
@s3rvac You could use Travis CI if you roll it incrementally initially, with ccache.
The `capstone2llvmir` target took _~30 minutes_ to build the first time, now with ccache it took only _74 seconds_(if you switch from the default linker, you will get this under 1 minute).

The steps here are:
- Set Travis on your repo, before accepting this PR
- When the PR is merged, let it make a full build with the `capstone2llvmir`, this will cache the most time-consuming build(LLVM) and then you can remove the line with the `capstone2llvmir` build and uncomment the other 2, to run the full build - let it finish and cache the build.
After this, you will have free time to even run some tests.

> RetDec build requires a C++14-capable compiler

You have `set(CMAKE_CXX_STANDARD 14)` in the CMakeLists.txt and Clang 5 fully supports it.
It seems to me that the issue here is that it uses the header from GCC 4.8, installed in the system.
Have to see yet what is the problem here - I also don't like that the GCC build ends up using GCC 4.8 through ccache, for some of the components.

**Comment by s3rvac** [comment]
> You could use Travis CI if you roll it incrementally initially, with ccache.

Unfortunately, I do not think that a partial support that requires manual "hacking" in `.travis.yml` will be desirable. We are currently discussing which CI system we should use, and we will definitely want to go with one that will enable hassle-free setup, use, and will be able to build and test the entire repository.

> You have set(CMAKE_CXX_STANDARD 14) in the CMakeLists.txt and Clang 5 fully supports it.
> It seems to me that the issue here is that it uses the header from GCC 4.8, installed in the system.
> Have to see yet what is the problem here - I also don't like that the GCC build ends up using GCC 4.8 through ccache, for some of the components.

Yeah, GCC 4.8 is not supported due to lacking C++14 support in the standard library. RetDec requires at least GCC 4.9.

**Comment by lilianmoraru** [comment]
> Unfortunately, I do not think that a partial support that requires manual "hacking" in .travis.yml will be desirable.

It is not "partial support" or "manual hacking", it is just a first step to cache the LLVM build and then it is "full support", "no manual hacking".
If you will change files in LLVM, it will rebuild the object files that need to be modified - it is still a full build.

**Comment by s3rvac** [comment]
I understand. I did not mean to discourage you. I am just afraid of the problems that such an incremental solution might cause us. For example, if we ever wanted to clear the cache and start building from scratch (e.g. if the incremental build starts failing), we would need to do the same thing again (build LLVM, then possibly build something else, then a full build). Otherwise, the build will start timeouting. Or is there something I am missing?

**Pull request closed without merging**
